run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
    - gofmt
    - goimports
    - ineffassign
    - unused
    - misspell
    - gosimple
    - gocritic

linters-settings:
  revive:
    rules:
      - name: var-naming
      - name: blank-imports
      - name: context-as-argument
      - name: error-return
      - name: error-strings
      - name: increment-decrement
      - name: receiver-naming
      - name: unexported-return

  goimports:
    local-prefixes: HM2

  govet:
    enable-all: true
    disable:
      - fieldalignment

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
